os:
  - linux
  - osx

language: R
sudo: false
cache: 
  packages: true
warnings_are_errors: FALSE


r:
  - oldrel
  - release
  - devel
  
r_packages:
 - covr
 - testthat

after_success:
    - Rscript -e 'covr::codecov()'