# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
warnings_are_errors: false

r_packages:
 - covr
 - testthat
 - igraph
 - tidyverse

after_success:
  - Rscript -e 'covr::codecov()'
  
language: R
sudo: false
cache: packages
R:
  - oldrel
  - release
  - devel
  
